apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: nodedns-reader-binding
subjects:
    - kind: ServiceAccount
      name: default
      namespace: kube-system
roleRef:
    kind: ClusterRole
    name: nodedns-reader
    apiGroup: rbac.authorization.k8s.io
